export const PERSONALIDADES = {
  GROQ1: "LIDER", GROQ2: "SABIO", GROQ3: "GUERRERO",
  FREE5: "HACKER", FREE6: "POETA", HF: "CIENTIFICO",
  OPENROUTER: "DIPLOMATICO", TOGETHER: "HERMANO", "META-BF-9": "SUPREMO"
};
